[project]
name = "sleep-monitor"
version = "0.9.0"
description = "Sleep monitoring system with camera recording and web viewer"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python>=4.8.0",
    "ruff>=0.13.2",
    "ty>=0.0.1a21",
]
